### ISSUE TITLE
Issue display when internet is not reachable

### ISSUE THREAD

**Issue by qlem** [doums/milcheck#2]
The display is broken when internet is not reachable.

### Screenshot
![screenshot](https://i.imgur.com/gpHsQt5.png)

### How to reproduce
Just turn off internet and run milcheck.

**Comment by doums** [comment]
Hi, the error message from curl is just normal.
But the display is fucked up because the error is printed right after the spinner and the program is exited without resetting the terminal.
I'll fix this. Thanks!
