### ISSUE TITLE
I think that certain variables are unsupported, but are supported by pacman

### ISSUE THREAD

**Issue by rickprice** [doums/milcheck#4]
I'm having an issue with my mirrors that look like the following:
It seems that $repo and $arch are not supported as substitutions in milcheck, but they are by pacman etc...

Not found! https://mirror.dkm.cz/manjaro/stable/$repo/$arch
Not found! https://mirrors.ucr.ac.cr/manjaro/stable/$repo/$arch
Not found! http://ftp.snt.utwente.nl/pub/linux/manjaro/stable/$repo/$arch
Not found! https://mirror.ufro.cl/manjaro/stable/$repo/$arch
Not found! https://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable/$repo/$arch
Not found! https://mirror.truenetwork.ru/manjaro/stable/$repo/$arch
Not found! https://mirror.zetup.net/manjaro/stable/$repo/$arch
Not found! http://ftp.free.org/mirrors/repo.manjaro.org/repos/stable/$repo/$arch
Not found! https://mirror.oldsql.cc/manjaro/stable/$repo/$arch
Not found! https://ftp.caliu.cat/pub/distribucions/manjaro/stable/$repo/$arch
Not found! https://mirror.netcologne.de/manjaro/stable/$repo/$arch
Not found! https://ct.mirror.garr.it/mirrors/manjaro/stable/$repo/$arch
Not found! https://repo.iut.ac.ir/repo/manjaro/stable/$repo/$arch
Not found! https://mirror.futureweb.be/manjaro/stable/$repo/$arch
Not found! http://ftp.vectranet.pl/manjaro/stable/$repo/$arch
Not found! https://ba.mirror.garr.it/mirrors/manjaro/stable/$repo/$arch
Not found! https://ftp.lysator.liu.se/pub/manjaro/stable/$repo/$arch
Not found! https://mirror.tuchola-dc.pl/manjaro/stable/$repo/$arch
Not found! http://mirror.is.co.za/mirrors/manjaro.org/stable/$repo/$arch
Not found! https://mirrors.netix.net/manjaro/stable/$repo/$arch
Not found! https://mirror.atysleaks.org/manjaro/stable/$repo/$arch
Not found! https://mirrors.huaweicloud.com/manjaro/stable/$repo/$arch
Not found! https://mirror.d-tl.com/manjaro/stable/$repo/$arch
Not found! http://ftp.tu-chemnitz.de/pub/linux/manjaro/stable/$repo/$arch
Not found! http://ftp.linux.org.tr/manjaro/stable/$repo/$arch
Not found! https://mirror1.cl.netactuate.com/manjaro/stable/$repo/$arch
Not found! https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/$repo/$arch
Not found! https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/$repo/$arch
Not found! https://ftp.halifax.rwth-aachen.de/manjaro/stable/$repo/$arch

Not found! https://mirror.dkm.cz/manjaro/stable/$repo/$arch
Not found! https://mirrors.ucr.ac.cr/manjaro/stable/$repo/$arch
Not found! http://ftp.snt.utwente.nl/pub/linux/manjaro/stable/$repo/$arch
Not found! https://mirror.ufro.cl/manjaro/stable/$repo/$arch
Not found! https://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable/$repo/$arch
Not found! https://mirror.truenetwork.ru/manjaro/stable/$repo/$arch
Not found! https://mirror.zetup.net/manjaro/stable/$repo/$arch
Not found! http://ftp.free.org/mirrors/repo.manjaro.org/repos/stable/$repo/$arch
Not found! https://mirror.oldsql.cc/manjaro/stable/$repo/$arch
Not found! https://ftp.caliu.cat/pub/distribucions/manjaro/stable/$repo/$arch
Not found! https://mirror.netcologne.de/manjaro/stable/$repo/$arch
Not found! https://ct.mirror.garr.it/mirrors/manjaro/stable/$repo/$arch
Not found! https://repo.iut.ac.ir/repo/manjaro/stable/$repo/$arch
Not found! https://mirror.futureweb.be/manjaro/stable/$repo/$arch
Not found! http://ftp.vectranet.pl/manjaro/stable/$repo/$arch
Not found! https://ba.mirror.garr.it/mirrors/manjaro/stable/$repo/$arch
Not found! https://ftp.lysator.liu.se/pub/manjaro/stable/$repo/$arch
Not found! https://mirror.tuchola-dc.pl/manjaro/stable/$repo/$arch
Not found! http://mirror.is.co.za/mirrors/manjaro.org/stable/$repo/$arch
Not found! https://mirrors.netix.net/manjaro/stable/$repo/$arch
Not found! https://mirror.atysleaks.org/manjaro/stable/$repo/$arch
Not found! https://mirrors.huaweicloud.com/manjaro/stable/$repo/$arch
Not found! https://mirror.d-tl.com/manjaro/stable/$repo/$arch
Not found! http://ftp.tu-chemnitz.de/pub/linux/manjaro/stable/$repo/$arch
Not found! http://ftp.linux.org.tr/manjaro/stable/$repo/$arch
Not found! https://mirror1.cl.netactuate.com/manjaro/stable/$repo/$arch
Not found! https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/$repo/$arch
Not found! https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/$repo/$arch
Not found! https://ftp.halifax.rwth-aachen.de/manjaro/stable/$repo/$arch

**Comment by mlmatlock** [comment]
Because...Manjaro?

```
uname -a
Linux Jammin1 5.11.7-arch1-1 #1 SMP PREEMPT Wed, 17 Mar 2021 16:59:58 +0000 x86_64 GNU/Linux
```

```
cat /etc/pacman.d/mirrorlist

Server = https://america.mirror.pkgbuild.com/$repo/os/$arch
```
```
milcheck
State Url                                  Protocol Country       Completion % Delay h:m Avg dur s Dev dur s Score
   Ok https://america.mirror.pkgbuild.com/ https    United States          100      0:00      0.39      0.01   0.4
```

**Comment by doums** [comment]
lol
